# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true


# Setup
title:               Pinstinct
tagline:             'Code'
description:         'code: <a href="https://github.com/pinstinct" target="_blank">Github</a></br> idea: <a href="https://twitter.com/pinstinct" target="_blank">@pinstinct</a>.'
url:                 https://pinstinct.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              LIM
  url:               https://twitter.com/pinstinct
  email:             gusals3407@gmail.com

# Custom vars
version:             1.1.2
