#
###################################
# Site wide configuration
####################################
#
title: Pinstinct
email: dev@limhm.com
description: A simple and awesome blog theme powered by jekyll.
url: https://blog.limhm.com # the base hostname & protocol for your site
keywords: ["Programming", "Web", "Python"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         pretty #/articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Pinstinct
  # avatar: leonids-logo.png
  job: "Software Developer"
  # bio: "A backend developer who loves awesome things."
  email: dev@limhm.com
  disqus-shortname: pinstinct07
  twitter: pinstinct #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: pinstinct #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
